### ISSUE TITLE
Unable to install addon

### ISSUE THREAD

**Issue by civarson** [sondregronas/ankermake-hass-component#11]
I'm getting an error when trying to install in HA > Addons from this repo:

`Failed to install add-on`
`The command '/bin/ash -o pipefail -c apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 127`

**Comment by sondregronas** [comment]
Hi @civarson

Thanks for pointing that out, oddly enough the addon has been _versionless_ for well over a month now, thought I caught it back then. Weird - but shouldn't happen again.

Can you please hit check for updates in the Home Assistant AddOn page and try again?

**Comment by civarson** [comment]
Success! - thanks very much.

**Comment by sondregronas** [comment]
Awesome 👍
