### ISSUE TITLE
nothing in hacs to install

### ISSUE THREAD

**Issue by Schnuecks** [sondregronas/ankermake-hass-component#13]
This integration is not on hacs anymore?

**Comment by sondregronas** [comment]
It appears the hacs workflows got disabled, I've re-enabled them now. You should still be able to add the integration by adding the repository to hacs, if it's not resolved already (this link hopefully works https://my.home-assistant.io/redirect/hacs_repository/?owner=sondregronas&repository=ankermake-hass-component&category=ankermake)

**Comment by Schnuecks** [comment]
![image](https://github.com/user-attachments/assets/4ba91542-cc9e-497e-baad-1b0ddb68253a)

**Comment by Schnuecks** [comment]
Ok, need a little bit more time now it's there, thanks

**Comment by sondregronas** [comment]
Awesome, thanks for reminding me to re-enable the workflows 🙂
